name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Add Coverage to PR
          id: jacoco
          uses: madrapps/jacoco-report@v1.3
          with:
            paths: ${{ github.workspace }}/build/reports/jacoco/testCoverage/testCoverage.xml
            token: ${{ secrets.GITHUB_TOKEN }}
            min-coverage-overall: 40
            min-coverage-changed-files: 60

