name: Jacoco Report

on:
  push:
  pull_request:

jobs:
  jacoco-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '19'  # Update with your desired Java version
          distribution: 'adopt'

      - name: Build and Test
        run: |
          chmod +x ./gradlew
          ./gradlew build
          ./gradlew AggregateJacocoReport

      - name: Upload Report
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
            name: coverage-report
            path: ${{ github.workspace }}/build/reports/jacoco/aggregate/jacocoTestReport.xml
            token: ${{ secrets.GITHUB_TOKEN }}