name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: Run tests
        run: ./gradlew AggregateJacocoReport
      - name: preserve coverage information in an easy-to-reach folder
        run: mv build/reports/jacoco/aggregate/html ./coverage
      - name: preserve coverage information in an easy-to-reach folder
        run: mv build/reports/jacoco/aggregate/jacocoTestReport.xml ./coverage/report.xml
      - name: preserve coverage information in an easy-to-reach folder
        run: echo `cat coverage/index.html | grep -o -E "Total[^%]+?%" | sed -E "s/<.*>//" | sed -E "s/Total/TestCoverage:/"`

