name: Jacoco Report

on:
  push:

jobs:
  jacoco-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '19'  # Update with your desired Java version
          distribution: 'adopt'

      - name: Build and Test
        run: |
          chmod +x ./gradlew
          ./gradlew build
          ./gradlew jacocoTestReport

      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
            name: coverage-report
            path: ${{ github.workspace }}/build/reports/jacoco/aggregate/jacocoTestReport.xml