name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: |
          chmod +x gradlew
          ./gradlew build
      - name: Run tests
        run: ./gradlew AggregateJacocoReport

      - name: Upload Report
        uses: 'actions/upload-artifact@v2'
        with:
          name: report.xml
          path: ${{ github.workspace }}/build/reports/jacoco/AggregateJacocoReport/AggregateJacocoReport.xml

      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.1
        with:
            path: ${{ github.workspace }}/build/reports/jacoco/AggregateJacocoReport/AggregateJacocoReport.xml
            token: ${{ secrets.GITHUB_TOKEN }}
            min-coverage-overall: 40
            min-coverage-changed-files: 60
            debug-mode: false

      - name: Get the Coverage info
        run: |
            echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
            echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"