name: Jacoco Report

on:
  push:

jobs:
  jacoco-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '19'  # Update with your desired Java version
          distribution: 'adopt'

      - name: Build and Test
        run: |
          chmod +x ./gradlew
          ./gradlew build
          ./gradlew test
          ./gradlew jacocoTestReport

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
            generate-branches-badge: true
            jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv